{
 "title": "Biblioteca General",
 "time": { "from": "2020-04-07T03:00:00.000Z", "to": "2020-04-10T02:59:59.000Z" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gente Dentro",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "Actualmente",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" }
       ],
       "measurement": "Personas",
       "query": "SELECT sum(\"value\") FROM \"Personas\" WHERE $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Ingresos",
     "type": "singlestat",
     "description": "Gente actualmente adentro",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Ingresos",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "entrar" }
       ]
      }
     ]
    },
    {
     "title": "Egresos",
     "type": "singlestat",
     "description": "Cuanta gente salió",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "alias": "Egresos",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "entrar" }
       ]
      }
     ]
    },
    {
     "title": "Ingresos y Egresos",
     "type": "graph",
     "gridPos": { "h": 11, "w": 18, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Ingresos",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"value\" > 0) AND $timeFilter GROUP BY time(10m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "entrar" }
       ]
      },
      {
       "alias": "Egresos",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "salir" }
       ]
      }
     ]
    },
    {
     "title": "Cantidad de personas",
     "type": "bargauge",
     "description": "Gente actualmente adentro",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "Ingresos",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "entrar" }
       ]
      },
      {
       "alias": "Egresos",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "accion", "operator": "=", "value": "salir" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "Errores",
       "groupBy": [
        { "params": [ "1d" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"value\" = 0) AND $timeFilter GROUP BY time(1d) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "value", "operator": "=", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "Errores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Errores",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Personas",
       "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"value\" = 0) AND $timeFilter GROUP BY time(1h) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "value", "operator": "=", "value": "0" }
       ]
      }
     ]
    }
   ]
  }
 ]
}