{
 "title": "Biblioteca Diario",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:00.000Z" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Permanencia Actual",
   "type": "gauge",
   "description": "Cuanta gente hay actualmente",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Actualmente",
     "measurement": "Personas",
     "query": "SELECT sum(\"value\") FROM \"Personas\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flujo Personas",
   "type": "bargauge",
   "description": "Ingresos y egresos",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Ingresos",
     "measurement": "Personas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "entrar" }
     ]
    },
    {
     "alias": "Egresos",
     "measurement": "Personas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "salir" }
     ]
    }
   ]
  },
  {
   "title": "Flujo de personas",
   "type": "stat",
   "description": "Flujo de personas",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Ingresos",
     "measurement": "Personas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "entrar" }
     ]
    },
    {
     "alias": "Egresos",
     "measurement": "Personas",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "salir" }
     ]
    }
   ]
  },
  {
   "title": "Permanencia x dia",
   "type": "bargauge",
   "description": "Cuanta gente se encuentra en la biblioteca",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_dia",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") from (SELECT sum(\"value\") as value from Personas group by time(1h), \"dia\" ) group by \"dia\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Permanencia",
   "type": "graph",
   "description": "Cuanta gente se encuentra en la biblioteca",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Permanencia",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Personas",
     "query": "SELECT cumulative_sum(sum(\"value\")) FROM \"Personas\" WHERE $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flujo de Personas",
   "type": "graph",
   "description": "Cuanta gente se encuentra en la biblioteca",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Flujo personas",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Personas",
     "query": "SELECT sum(\"value\") FROM \"Personas\" WHERE $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ingresos y Egresos",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Ingresos",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Personas",
     "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"value\" > 0) AND $timeFilter GROUP BY time(10m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "entrar" }
     ]
    },
    {
     "alias": "Egresos",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Personas",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "=", "value": "salir" }
     ]
    }
   ]
  },
  { "title": "Errores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Errores",
   "type": "gauge",
   "description": "Errores Acumulados",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Errores",
     "measurement": "Personas",
     "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"accion\" != 'entrar' AND \"accion\" != 'salir') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "!=", "value": "entrar" },
      { "condition": "AND", "key": "accion", "operator": "!=", "value": "salir" }
     ]
    }
   ]
  },
  {
   "title": "Errores",
   "type": "graph",
   "description": "Errores Agregados",
   "gridPos": { "h": 7, "w": 15, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errores",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Personas",
     "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"accion\" != 'entrar' AND \"accion\" != 'salir') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "!=", "value": "entrar" },
      { "condition": "AND", "key": "accion", "operator": "!=", "value": "salir" }
     ]
    }
   ]
  },
  {
   "title": "Errores",
   "type": "graph",
   "description": "Errores agrupados",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errores",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Personas",
     "query": "SELECT count(\"value\") FROM \"Personas\" WHERE (\"accion\" != 'entrar' AND \"accion\" != 'salir') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "accion", "operator": "!=", "value": "entrar" },
      { "condition": "AND", "key": "accion", "operator": "!=", "value": "salir" }
     ]
    }
   ]
  }
 ]
}